# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_focus_new_timesTwo`, x)
}

focus_offline <- function(Y, threshold, family, theta0, args, adp_max_check) {
    .Call(`_focus_new_focus_offline`, Y, threshold, family, theta0, args, adp_max_check)
}

