# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

focus_offline <- function(Z, threshold, family, theta0, args, adp_max_check) {
    .Call(`_exfocus_rcpp_focus_offline`, Z, threshold, family, theta0, args, adp_max_check)
}

.npfocus_offline <- function(Y, quants, theta0, args, adp_max_check) {
    .Call(`_exfocus_rcpp_npfocus_offline`, Y, quants, theta0, args, adp_max_check)
}

